version: '3'

services:
  app:
    build: 
      context: node
    image: brenomachadodomonte/node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 --timeout 30s docker-entrypoint.sh
    command: node index.js
    networks:
      - nodenet
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: brenomachadodomonte/nginx
    container_name: nginx
    entrypoint: dockerize -wait tcp://app:3000 --timeout 30s
    command: nginx -g 'daemon off;'
    networks:
      - nodenet
    ports:
      - "8080:80"
    depends_on:
      - app 

  db:
    image: mariadb
    command: --innodb-use-native-aio=0
    container_name: maria-db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge