version: '3'

services:

  laravel:
    build: 
      context: ./php-laravel
      dockerfile: Dockerfile.prod
    image: brenomachadodomonte/php-laravel:prod
    container_name: laravel
    networks:
      - laranet
  
  nginx:
    build: 
      context: ./proxy-reverso
      dockerfile: Dockerfile
    image: brenomachadodomonte/proxy-reverso:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge