version: '3'

services:

  laravel:
    image: brenomachadodomonte/php-laravel:prod
    container_name: laravel
    networks:
      - "laranet"
  
  nginx:
    image: brenomachadodomonte/proxy-reverso:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge